# Generated by Django 3.0.5 on 2020-05-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20200521_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='', max_length=250),
        ),
    ]
