# Generated by Django 3.0.5 on 2020-05-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='price',
        ),
        migrations.AddField(
            model_name='store',
            name='price_TT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='store',
            name='price_retail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
