# Generated by Django 3.0.5 on 2020-05-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20200521_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SubCategory',
            new_name='subcategory',
        ),
    ]
